version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      RESEND_API_KEY: ${RESEND_API_KEY}
      CLIENT_EMAIL: ${CLIENT_EMAIL}
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium
    volumes:
      - whatsapp-session:/app/.wwebjs_auth
      - whatsapp-cache:/app/.wwebjs_cache
    restart: unless-stopped

volumes:
  whatsapp-session:
  whatsapp-cache:
