[phases.setup]
aptPkgs = [
  "chromium",
  "chromium-sandbox",
  "fonts-liberation",
  "fonts-noto-color-emoji",
  "libasound2",
  "libatk-bridge2.0-0",
  "libatk1.0-0",
  "libatspi2.0-0",
  "libcups2",
  "libdbus-1-3",
  "libdrm2",
  "libgbm1",
  "libgtk-3-0",
  "libnspr4",
  "libnss3",
  "libwayland-client0",
  "libxcomposite1",
  "libxdamage1",
  "libxfixes3",
  "libxkbcommon0",
  "libxrandr2",
  "libxshmfence1",
  "xdg-utils",
  "curl",
  "wget"
]
nixPkgs = ["bun"]

[phases.install]
cmds = ["bun install --production"]

[start]
cmd = "bun run index.js"

[variables]
PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium"
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
NODE_ENV = "production"
